package etfmonitor

import (
	"encoding/json"
	"math"
	"os"
	"testing"
	"time"
)

// The fixtures are generated by calling kite/betashares/screen.py's own
// metrics() — not by reimplementing it — so these tests pin the Go port to the
// validated Python screener the way nserotator is pinned to momentum.py.
// Regenerate: see docs/specs/21-asx-etf-monitor.md §Testing.

type fixture struct {
	Closes       []float64 `json:"closes"`
	M3           *float64  `json:"m3"`
	M6           *float64  `json:"m6"`
	M12          *float64  `json:"m12"`
	TrendUp      *bool     `json:"sma200_trend_up"`
	Vol          float64   `json:"vol"`
	MaxDD        float64   `json:"maxdd"`
	Days         int       `json:"days"`
	HasDataBreak bool      `json:"has_data_break"`
}

func loadFixtures(t *testing.T) map[string]fixture {
	t.Helper()
	raw, err := os.ReadFile("testdata/screen_py_fixtures.json")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var out map[string]fixture
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("parse fixtures: %v", err)
	}
	if len(out) == 0 {
		t.Fatal("no fixtures")
	}
	return out
}

func seriesFrom(closes []float64) Series {
	start := time.Date(2023, 1, 2, 0, 0, 0, 0, time.UTC)
	s := Series{Ticker: "TEST"}
	for i, c := range closes {
		s.Candles = append(s.Candles, Candle{Date: start.AddDate(0, 0, i), Close: c})
	}
	return s
}

func closeTo(a, b, tol float64) bool { return math.Abs(a-b) <= tol }

// TestSignalMathPinnedToScreenPy is the table-driven pin: every metric the Go
// port computes must match the Python reference on the same closes.
func TestSignalMathPinnedToScreenPy(t *testing.T) {
	const tol = 1e-9
	lookbacks := []int{63, 126, 252}

	for name, f := range loadFixtures(t) {
		t.Run(name, func(t *testing.T) {
			m := Compute(seriesFrom(f.Closes), lookbacks, 200)

			if m.Days != f.Days {
				t.Errorf("days = %d want %d", m.Days, f.Days)
			}
			for i, want := range []*float64{f.M3, f.M6, f.M12} {
				got := m.Returns[i]
				if want == nil {
					if got.OK {
						t.Errorf("return[%d] = %v, want unavailable", i, got.Value)
					}
					continue
				}
				if !got.OK {
					t.Errorf("return[%d] unavailable, want %v", i, *want)
					continue
				}
				if !closeTo(got.Value, *want, tol) {
					t.Errorf("return[%d] = %.12f want %.12f", i, got.Value, *want)
				}
			}
			if !closeTo(m.Vol, f.Vol, 1e-9) {
				t.Errorf("vol = %.12f want %.12f", m.Vol, f.Vol)
			}
			if !closeTo(m.MaxDD, f.MaxDD, 1e-9) {
				t.Errorf("maxDD = %.12f want %.12f", m.MaxDD, f.MaxDD)
			}
			if f.TrendUp == nil {
				if m.HasTrend {
					t.Errorf("HasTrend = true, want no trend read")
				}
			} else if !m.HasTrend {
				t.Errorf("HasTrend = false, want %v", *f.TrendUp)
			} else if m.TrendUp != *f.TrendUp {
				t.Errorf("TrendUp = %v want %v", m.TrendUp, *f.TrendUp)
			}
		})
	}
}

// TestSplitGuardRejectsUnadjustedSplit is mandatory (spec 21 §Bad-data guard).
// The "split" fixture is the BBUS/BBOZ signature: without the guard its
// corrupted vol (830%) and drawdown (-93%) enter the ranking as if real.
func TestSplitGuardRejectsUnadjustedSplit(t *testing.T) {
	fx := loadFixtures(t)
	for name, f := range fx {
		s := seriesFrom(f.Closes)
		_, broken := DataBreak(s, DataBreakThreshold)
		if broken != f.HasDataBreak {
			t.Errorf("%s: DataBreak = %v want %v", name, broken, f.HasDataBreak)
		}
	}

	split := fx["split"]
	if !split.HasDataBreak {
		t.Fatal("fixture 'split' should contain a data break")
	}
	// The corruption is real and large — this is what the guard prevents from
	// being ranked.
	m := Compute(seriesFrom(split.Closes), []int{63, 126, 252}, 200)
	if m.Vol < 1.0 {
		t.Errorf("expected absurd vol from the unadjusted split, got %.2f", m.Vol)
	}
	if m.MaxDD > -0.9 {
		t.Errorf("expected catastrophic maxDD from the unadjusted split, got %.2f", m.MaxDD)
	}
}

// TestSplitGuardRejectsRatherThanRanksFirst is the end-to-end statement of the
// requirement: a spiking series must not out-rank a clean one.
func TestSplitGuardRejectsRatherThanRanksFirst(t *testing.T) {
	// A fund that doubles overnight and holds the gain: +100% momentum on
	// nothing but a missing split divisor.
	spike := make([]float64, 300)
	for i := range spike {
		spike[i] = 100
		if i >= 150 {
			spike[i] = 200
		}
	}
	clean := make([]float64, 300)
	for i := range clean {
		clean[i] = 100 * math.Pow(1.001, float64(i))
	}

	spikeSeries, cleanSeries := seriesFrom(spike), seriesFrom(clean)
	if _, broken := DataBreak(spikeSeries, DataBreakThreshold); !broken {
		t.Fatal("split guard failed to flag a 2x overnight gap")
	}
	if _, broken := DataBreak(cleanSeries, DataBreakThreshold); broken {
		t.Fatal("split guard false-positived on a clean compounding series")
	}

	// Without the guard the spike would win outright — confirm that it would.
	lb := []int{63, 126, 252}
	spikeScore, _ := Score(Compute(spikeSeries, lb, 200).Returns, []float64{0.5, 0.3, 0.2})
	cleanScore, _ := Score(Compute(cleanSeries, lb, 200).Returns, []float64{0.5, 0.3, 0.2})
	if spikeScore <= cleanScore {
		t.Fatalf("expected the corrupted series to out-score the clean one (%.3f vs %.3f) — "+
			"that is precisely why it must be rejected before ranking", spikeScore, cleanScore)
	}
}

func TestTrailingReturnInsufficientHistory(t *testing.T) {
	closes := make([]float64, 60)
	for i := range closes {
		closes[i] = 100
	}
	if r := TrailingReturn(closes, 63); r.OK {
		t.Errorf("expected unavailable with 60 sessions and a 63-day lookback, got %v", r.Value)
	}
	if r := TrailingReturn(closes, 30); !r.OK {
		t.Error("expected a return with 60 sessions and a 30-day lookback")
	}
}

func TestSMARequiresFullWindow(t *testing.T) {
	closes := make([]float64, 199)
	for i := range closes {
		closes[i] = 100
	}
	if _, ok := SMA(closes, 200); ok {
		t.Error("SMA(200) should be unavailable with 199 sessions")
	}
	closes = append(closes, 100)
	if v, ok := SMA(closes, 200); !ok || !closeTo(v, 100, 1e-12) {
		t.Errorf("SMA(200) = %v ok=%v want 100", v, ok)
	}
}
